### ISSUE TITLE
AWP | Fade does not render on Apple platforms

### ISSUE THREAD

**Issue by tsd** [vanta240i/BF-Issues#12]
See attached. Effect appeared after changing from AWP to Fade, if it renders, try doing it multiple times.

![image](https://user-images.githubusercontent.com/70513548/185496289-6da5faab-962d-4763-8755-2ebc70b4e2d2.png)

**Comment by vanta240i** [comment]
A fix was discovered. This only happens to players that update, not to new players, so clicking default all settings before playing, and then re-logging in can help fix this.
