### ISSUE TITLE
BFR crashing on android

### ISSUE THREAD

**Issue by hypex12x** [vanta240i/BF-Issues#2]
https://youtu.be/adqen4u0Sow

**Comment by vanta240i** [comment]
I know I asked you this already, but please specify 3 things:

1. Device (I think it was the Samsung S2 Tab?)
2. Have you previously installed BFR?
3. Android Version

**Comment by vanta240i** [comment]
No response although I assume issue is related with the others, so it will be fixed with next version (?)
