### ISSUE TITLE
Bfr not loading on android

### ISSUE THREAD

**Issue by ghost** [vanta240i/BF-Issues#6]
When I try to launch block force remastered it doesn't loading it is just stuck on "Block force remastered Icycube games" title

**Comment by ghost** [comment]
https://youtube.com/shorts/RWcJMv6Axqs?feature=share 
device name: Xiaomi redmi 6
Android version: 9 PPR1.180610.011

**Comment by vanta240i** [comment]
Will be fixed with next version.

**Comment by ghost** [comment]
Ok
