### ISSUE TITLE
App runs with black borders around the display on larger screen Apple devices

### ISSUE THREAD

**Issue by tsd** [vanta240i/BF-Issues#8]
Has been reported before, not as an issue though. This type of issue is possibly due to BFR not having support for New Apple display API's, see: https://developer.apple.com/news/?id=oefg5bhp&1632770922

- Device: Apple iPad Pro (5th Generation, 12.9 Inch)
- Latest TestFlight build

![image](https://user-images.githubusercontent.com/70513548/185494115-18d599c7-27b3-4cca-a886-1b3e3a816b8f.png)

**Comment by vanta240i** [comment]
Thank you for linking apple's article as that was very helpful, will fix it in the next update.

**Comment by vanta240i** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/102895212/194930001-db46440d-f512-4767-8b56-640a3693ebc3.png">
Should be fixed on next versions.
